version: '3'
services:
  server:
    build:
      context: ./server
    container_name: health_wellness_server 
    ports:
      - 3005:3000
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports: 
      - 3004:5000
